// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFHck9LZO7boGqQDz-w1tHo9g6uieC1kg',
    appId: '1:227734802025:web:98227422af80a7d2ed1cf8',
    messagingSenderId: '227734802025',
    projectId: 'spotify-7496e',
    authDomain: 'spotify-7496e.firebaseapp.com',
    storageBucket: 'spotify-7496e.appspot.com',
    measurementId: 'G-D8QP60FNN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxIPvYaEzZZ-dltwH-JRPGkaYZbDmRqJw',
    appId: '1:227734802025:android:6bbc7e0834a66cc7ed1cf8',
    messagingSenderId: '227734802025',
    projectId: 'spotify-7496e',
    storageBucket: 'spotify-7496e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj145kzceOz_RopeAvaZp4byXaLP6651g',
    appId: '1:227734802025:ios:9aa6f14449ec9afced1cf8',
    messagingSenderId: '227734802025',
    projectId: 'spotify-7496e',
    storageBucket: 'spotify-7496e.appspot.com',
    iosBundleId: 'com.tyukmaev.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj145kzceOz_RopeAvaZp4byXaLP6651g',
    appId: '1:227734802025:ios:9aa6f14449ec9afced1cf8',
    messagingSenderId: '227734802025',
    projectId: 'spotify-7496e',
    storageBucket: 'spotify-7496e.appspot.com',
    iosBundleId: 'com.tyukmaev.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFHck9LZO7boGqQDz-w1tHo9g6uieC1kg',
    appId: '1:227734802025:web:4ae82e0b72a1744ced1cf8',
    messagingSenderId: '227734802025',
    projectId: 'spotify-7496e',
    authDomain: 'spotify-7496e.firebaseapp.com',
    storageBucket: 'spotify-7496e.appspot.com',
    measurementId: 'G-45SM1XSQRD',
  );
}
